services:
  ordsurg:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ordsurg
    restart: unless-stopped
    depends_on:
      - postgres17_external
    environment:
      POSTGRES_DB: orderingsurgery
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: pgdb
      POSTGRES_PORT: "5432"

      DJANGO_SETTINGS_MODULE: core.settings
      DEBUG: "1"
      SECRET_KEY: "CpYtHoN"
    ports:
      - "8686:8000"
    networks:
      - shared_network

  postgres17_external:
    image: tianon/true
    container_name: postgres17_external
    depends_on: []
    networks:
      - shared_network

networks:
  shared_network:
    external: true
